export interface Logo {
  name: string
  industry: string
  founded: number
  funFact: string
  /** Path to the logo's SVG file under public/. */
  icon: string
  /** Intrinsic width/height ratio of the icon, used to size it in the physics pile. */
  aspect: number
  /** Link to the project's GitHub repository. */
  gitLink: string
}

export const LOGOS: Logo[] = [
  {
    name: "Vue.js",
    industry: "JavaScript framework",
    founded: 2014,
    funFact:
      "Vue was created by Evan You after working at Google, aiming to pull the best parts of Angular into something lighter.",
    icon: "/logos/vue.svg",
    aspect: 1.158,
    gitLink: "https://github.com/vuejs/core",
  },
  {
    name: "React",
    industry: "JavaScript library",
    founded: 2013,
    funFact:
      "React was originally built for Facebook's News Feed and only open-sourced in 2013 after engineer Jordan Walke championed it internally.",
    icon: "/logos/react.svg",
    aspect: 1.123,
    gitLink: "https://github.com/facebook/react",
  },
  {
    name: "Preact",
    industry: "JavaScript library",
    founded: 2015,
    funFact: "Preact reimplements the React API in about 3KB of JavaScript, roughly a tenth the size of React itself.",
    icon: "/logos/preact.svg",
    aspect: 0.865,
    gitLink: "https://github.com/preactjs/preact",
  },
  {
    name: "Ember.js",
    industry: "JavaScript framework",
    founded: 2011,
    funFact: "Ember.js grew out of the earlier SproutCore project and was named by co-creator Yehuda Katz.",
    icon: "/logos/emberjs.svg",
    aspect: 1.002,
    gitLink: "https://github.com/emberjs/ember.js",
  },
  {
    name: "D3.js",
    industry: "Data visualization",
    founded: 2011,
    funFact: "D3 stands for Data-Driven Documents and was created by Mike Bostock as part of his PhD work at Stanford.",
    icon: "/logos/d3.svg",
    aspect: 1.053,
    gitLink: "https://github.com/d3/d3",
  },
  {
    name: "Chart.js",
    industry: "Data visualization",
    founded: 2013,
    funFact:
      "Chart.js renders every chart on an HTML5 canvas element instead of SVG, a deliberate choice for performance with large datasets.",
    icon: "/logos/chartjs.svg",
    aspect: 0.865,
    gitLink: "https://github.com/chartjs/Chart.js",
  },
  {
    name: "React Router",
    industry: "Routing library",
    founded: 2014,
    funFact:
      "React Router predates React's official Context API and originally had to build its own workaround to pass routing data down the component tree.",
    icon: "/logos/react-router.svg",
    aspect: 1.829,
    gitLink: "https://github.com/remix-run/react-router",
  },
  {
    name: "React Hook Form",
    industry: "Form library",
    founded: 2019,
    funFact: "React Hook Form minimizes re-renders by keeping form state largely outside of React's own state system.",
    icon: "/logos/react-hook-form.svg",
    aspect: 1,
    gitLink: "https://github.com/react-hook-form/react-hook-form",
  },
  {
    name: "React Spring",
    industry: "Animation library",
    founded: 2018,
    funFact:
      "react-spring animates based on physical spring parameters like tension and friction rather than fixed durations and easing curves.",
    icon: "/logos/react-spring.svg",
    aspect: 1,
    gitLink: "https://github.com/pmndrs/react-spring",
  },
  {
    name: "Vuetify",
    industry: "UI component library",
    founded: 2016,
    funFact: "Vuetify was one of the first component frameworks to fully implement Google's Material Design spec for Vue.",
    icon: "/logos/vuetifyjs.svg",
    aspect: 1.153,
    gitLink: "https://github.com/vuetifyjs/vuetify",
  },
  {
    name: "VueUse",
    industry: "Utility library",
    founded: 2019,
    funFact: "VueUse packages over 200 small composition utilities, from mouse trackers to browser API wrappers, into one collection.",
    icon: "/logos/vueuse.svg",
    aspect: 0.924,
    gitLink: "https://github.com/vueuse/vueuse",
  },
  {
    name: "PrimeVue",
    industry: "UI component library",
    founded: 2018,
    funFact:
      "PrimeVue is built by PrimeTek, the same team behind the long-running PrimeFaces and PrimeNG UI libraries for other frameworks.",
    icon: "/logos/primevue.svg",
    aspect: 1,
    gitLink: "https://github.com/primefaces/primevue",
  },
  {
    name: "Chakra UI",
    industry: "UI component library",
    founded: 2019,
    funFact: "Chakra UI was created by Segun Adebayo and builds WAI-ARIA accessibility compliance into its components by default.",
    icon: "/logos/chakra-ui.svg",
    aspect: 1,
    gitLink: "https://github.com/chakra-ui/chakra-ui",
  },
  {
    name: "daisyUI",
    industry: "UI component library",
    founded: 2021,
    funFact: "daisyUI adds semantic class names like 'btn' and 'card' on top of Tailwind CSS, so components don't need long utility-class chains.",
    icon: "/logos/daisyui.svg",
    aspect: 1,
    gitLink: "https://github.com/saadeghi/daisyui",
  },
  {
    name: "Effect",
    industry: "Programming library",
    founded: 2021,
    funFact: "Effect brings a fully typed, composable effect system to TypeScript, drawing heavily on ideas from Scala's ZIO library.",
    icon: "/logos/effect.svg",
    aspect: 1,
    gitLink: "https://github.com/Effect-TS/effect",
  },
  {
    name: "ElysiaJS",
    industry: "Web framework",
    founded: 2022,
    funFact: "ElysiaJS is built specifically for the Bun runtime and leans on TypeScript's type system to validate requests at compile time.",
    icon: "/logos/elysiajs.svg",
    aspect: 1,
    gitLink: "https://github.com/elysiajs/elysia",
  },
  {
    name: "Go",
    industry: "Programming language",
    founded: 2009,
    funFact: "Go was designed at Google specifically to speed up compile times on the company's massive codebases, ditching many features of C++.",
    icon: "/logos/go.svg",
    aspect: 2.667,
    gitLink: "https://github.com/golang/go",
  },
  {
    name: "Python",
    industry: "Programming language",
    founded: 1991,
    funFact: "Python is named after the British comedy show Monty Python's Flying Circus, not the snake.",
    icon: "/logos/python.svg",
    aspect: 1.004,
    gitLink: "https://github.com/python/cpython",
  },
  {
    name: "Ruby",
    industry: "Programming language",
    founded: 1995,
    funFact: "Ruby was designed to make programmers happy, a stated goal of creator Yukihiro Matsumoto from day one.",
    icon: "/logos/ruby.svg",
    aspect: 1.004,
    gitLink: "https://github.com/ruby/ruby",
  },
  {
    name: "Kotlin",
    industry: "Programming language",
    founded: 2011,
    funFact: "Kotlin is named after Kotlin Island near St. Petersburg, echoing Java's own naming after the island of Java.",
    icon: "/logos/kotlin.svg",
    aspect: 1,
    gitLink: "https://github.com/JetBrains/kotlin",
  },
  {
    name: "Dart",
    industry: "Programming language",
    founded: 2011,
    funFact:
      "Dart was originally pitched by Google as a possible replacement for JavaScript in browsers before it found its true home powering Flutter.",
    icon: "/logos/dart.svg",
    aspect: 1,
    gitLink: "https://github.com/dart-lang/sdk",
  },
  {
    name: "Haskell",
    industry: "Programming language",
    founded: 1990,
    funFact: "Haskell is named after the logician Haskell Curry, whose work also inspired the term 'currying'.",
    icon: "/logos/haskell.svg",
    aspect: 1.414,
    gitLink: "https://github.com/ghc/ghc",
  },
  {
    name: "Fortran",
    industry: "Programming language",
    founded: 1957,
    funFact:
      "Fortran, short for 'Formula Translation', is considered the first widely used high-level programming language and is still used in scientific computing today.",
    icon: "/logos/fortran.svg",
    aspect: 1,
    gitLink: "https://github.com/fortran-lang/fortran-lang.org",
  },
  {
    name: "Crystal",
    industry: "Programming language",
    founded: 2014,
    funFact: "Crystal compiles to native code but reads almost like Ruby, a deliberate design goal of its creators.",
    icon: "/logos/crystal.svg",
    aspect: 1,
    gitLink: "https://github.com/crystal-lang/crystal",
  },
  {
    name: "Argo",
    industry: "Kubernetes workflow engine",
    founded: 2017,
    funFact:
      "Argo started as a container-native workflow engine at Applatix before being donated to the Cloud Native Computing Foundation.",
    icon: "/logos/argo.svg",
    aspect: 0.783,
    gitLink: "https://github.com/argoproj/argo-workflows",
  },
  {
    name: "Biome",
    industry: "Linter and formatter",
    founded: 2023,
    funFact:
      "Biome began as a community fork of the abandoned Rome toolchain, rebuilt by former Rome maintainers in a single Rust codebase.",
    icon: "/logos/biomejs.svg",
    aspect: 1.153,
    gitLink: "https://github.com/biomejs/biome",
  },
  {
    name: "Bower",
    industry: "Package manager",
    founded: 2012,
    funFact: "Bower was created at Twitter to manage front-end dependencies before npm and Yarn made it largely obsolete.",
    icon: "/logos/bower.svg",
    aspect: 1.138,
    gitLink: "https://github.com/bower/bower",
  },
  {
    name: "Chromatic",
    industry: "Visual testing platform",
    founded: 2017,
    funFact:
      "Chromatic is built by the same team behind Storybook and was designed specifically to catch UI regressions with visual snapshots.",
    icon: "/logos/chromatic.svg",
    aspect: 1,
    gitLink: "https://github.com/chromaui/chromatic-cli",
  },
  {
    name: "CircleCI",
    industry: "CI/CD platform",
    founded: 2011,
    funFact: "CircleCI was one of the first hosted continuous integration services to support Docker-based build environments.",
    icon: "/logos/circleci.svg",
    aspect: 0.988,
    gitLink: "https://github.com/CircleCI-Public",
  },
  {
    name: "Codecov",
    industry: "Code coverage platform",
    founded: 2013,
    funFact:
      "Codecov grew out of a hackathon project before becoming one of the most widely used coverage-reporting tools for open source projects.",
    icon: "/logos/codecov.svg",
    aspect: 1.045,
    gitLink: "https://github.com/codecov",
  },
  {
    name: "Cucumber",
    industry: "Behavior-driven testing",
    founded: 2008,
    funFact:
      "Cucumber popularized writing tests in plain-English 'Gherkin' syntax so non-programmers could read and help write test specifications.",
    icon: "/logos/cucumber.svg",
    aspect: 0.874,
    gitLink: "https://github.com/cucumber/cucumber",
  },
  {
    name: "Cypress",
    industry: "End-to-end testing",
    founded: 2015,
    funFact:
      "Cypress runs tests directly inside the browser rather than driving it remotely, giving it native access to everything happening on the page.",
    icon: "/logos/cypress.svg",
    aspect: 1,
    gitLink: "https://github.com/cypress-io/cypress",
  },
  {
    name: "Datadog",
    industry: "Monitoring platform",
    founded: 2010,
    funFact:
      "Datadog was founded by two engineers who met while working at IBM and Boxever, prompted by their own frustration debugging distributed systems.",
    icon: "/logos/datadog.svg",
    aspect: 0.931,
    gitLink: "https://github.com/DataDog",
  },
  {
    name: "Dependabot",
    industry: "Dependency automation",
    founded: 2017,
    funFact:
      "Dependabot began as an independent startup before GitHub acquired it in 2019 and folded it directly into repository security features.",
    icon: "/logos/dependabot.svg",
    aspect: 0.934,
    gitLink: "https://github.com/dependabot",
  },
  {
    name: "Docker",
    industry: "Containerization platform",
    founded: 2013,
    funFact:
      "Docker began as an internal tool at the PaaS company dotCloud before being spun out and open-sourced, popularizing containers industry-wide.",
    icon: "/logos/docker.svg",
    aspect: 1.384,
    gitLink: "https://github.com/docker/docker-ce",
  },
  {
    name: "Doctrine",
    industry: "PHP ORM",
    founded: 2006,
    funFact:
      "Doctrine's object-relational mapper was inspired directly by Hibernate, bringing the same 'Data Mapper' pattern from Java into the PHP ecosystem.",
    icon: "/logos/doctrine.svg",
    aspect: 0.755,
    gitLink: "https://github.com/doctrine/orm",
  },
  {
    name: "Docusaurus",
    industry: "Documentation framework",
    founded: 2017,
    funFact: "Docusaurus was built at Meta to power its own open-source documentation sites before being released for everyone to use.",
    icon: "/logos/docusaurus.svg",
    aspect: 1.174,
    gitLink: "https://github.com/facebook/docusaurus",
  },
  {
    name: "Drizzle",
    industry: "TypeScript ORM",
    founded: 2022,
    funFact:
      "Drizzle ORM generates SQL that stays close to what you'd write by hand, aiming to be a thin, fully type-safe layer rather than a heavy abstraction.",
    icon: "/logos/drizzle.svg",
    aspect: 1.18,
    gitLink: "https://github.com/drizzle-team/drizzle-orm",
  },
  {
    name: "esbuild",
    industry: "JavaScript bundler",
    founded: 2020,
    funFact:
      "esbuild was written from scratch in Go by Evan Wallace, co-founder of Figma, to prove that JavaScript bundlers could be orders of magnitude faster.",
    icon: "/logos/esbuild.svg",
    aspect: 1,
    gitLink: "https://github.com/evanw/esbuild",
  },
  {
    name: "ESLint",
    industry: "JavaScript linter",
    founded: 2013,
    funFact:
      "ESLint was created by Nicholas C. Zakas specifically so every linting rule could be individually enabled, disabled, or written as a plugin.",
    icon: "/logos/eslint.svg",
    aspect: 1.138,
    gitLink: "https://github.com/eslint/eslint",
  },
  {
    name: "Expo",
    industry: "React Native platform",
    founded: 2012,
    funFact:
      "Expo lets developers build and update React Native apps without touching native Xcode or Android Studio projects for most common features.",
    icon: "/logos/expo.svg",
    aspect: 1.108,
    gitLink: "https://github.com/expo/expo",
  },
  {
    name: "Faker",
    industry: "Fake data generator",
    founded: 2011,
    funFact:
      "Faker.js briefly disappeared from npm in 2022 after its original author intentionally sabotaged the package; the community immediately forked it as @faker-js/faker.",
    icon: "/logos/faker.svg",
    aspect: 0.831,
    gitLink: "https://github.com/faker-js/faker",
  },
  {
    name: "Fastify",
    industry: "Node.js web framework",
    founded: 2016,
    funFact:
      "Fastify was built around a schema-based approach to serialization, letting it validate and serialize JSON significantly faster than most Node frameworks.",
    icon: "/logos/fastify.svg",
    aspect: 1.552,
    gitLink: "https://github.com/fastify/fastify",
  },
  {
    name: "Firebase",
    industry: "App development platform",
    founded: 2011,
    funFact:
      "Firebase began as a real-time chat API startup called Envolve before pivoting entirely to its now-famous realtime database, and was acquired by Google in 2014.",
    icon: "/logos/firebase.svg",
    aspect: 0.795,
    gitLink: "https://github.com/firebase/firebase-js-sdk",
  },
  {
    name: "Flow",
    industry: "Static type checker",
    founded: 2014,
    funFact:
      "Flow was built at Facebook to add static typing to JavaScript years before TypeScript became the dominant choice for typed React codebases.",
    icon: "/logos/flow.svg",
    aspect: 0.959,
    gitLink: "https://github.com/facebook/flow",
  },
  {
    name: "Flutter",
    industry: "Cross-platform UI framework",
    founded: 2017,
    funFact:
      "Flutter renders every pixel itself with its own graphics engine instead of using native platform widgets, so apps look identical on iOS and Android.",
    icon: "/logos/flutter.svg",
    aspect: 0.808,
    gitLink: "https://github.com/flutter/flutter",
  },
  {
    name: "Fresh",
    industry: "Web framework",
    founded: 2022,
    funFact:
      "Fresh is Deno's own web framework and ships zero JavaScript to the client by default, hydrating only the interactive 'islands' of a page.",
    icon: "/logos/fresh.svg",
    aspect: 1.185,
    gitLink: "https://github.com/denoland/fresh",
  },
  {
    name: "Gatsby",
    industry: "Static site generator",
    founded: 2015,
    funFact:
      "Gatsby pulls data from any source into a single GraphQL layer at build time, whether that source is a CMS, Markdown files, or an API.",
    icon: "/logos/gatsby.svg",
    aspect: 1,
    gitLink: "https://github.com/gatsbyjs/gatsby",
  },
  {
    name: "GitHub Actions",
    industry: "CI/CD platform",
    founded: 2018,
    funFact:
      "GitHub Actions launched with the ability to package build steps as portable, shareable actions, turning CI configuration itself into an open-source ecosystem.",
    icon: "/logos/github-actions.svg",
    aspect: 1,
    gitLink: "https://github.com/actions",
  },
  {
    name: "Google Cloud",
    industry: "Cloud platform",
    founded: 2008,
    funFact:
      "Google Cloud's first public product was App Engine in 2008, built on the same infrastructure that powered Google Search internally.",
    icon: "/logos/google-cloud.svg",
    aspect: 1.243,
    gitLink: "https://github.com/googleapis/google-cloud-node",
  },
  {
    name: "Gradle",
    industry: "Build automation tool",
    founded: 2007,
    funFact:
      "Gradle combined the flexibility of Ant with the dependency management of Maven, using Groovy (and later Kotlin) scripts instead of rigid XML.",
    icon: "/logos/gradle.svg",
    aspect: 1.362,
    gitLink: "https://github.com/gradle/gradle",
  },
  {
    name: "Grafana",
    industry: "Observability platform",
    founded: 2014,
    funFact:
      "Grafana started as a fork of Kibana that swapped in richer, more flexible time-series graphing before growing into its own independent project.",
    icon: "/logos/grafana.svg",
    aspect: 0.918,
    gitLink: "https://github.com/grafana/grafana",
  },
  {
    name: "GraphQL",
    industry: "Query language",
    founded: 2015,
    funFact:
      "GraphQL was developed internally at Facebook in 2012 to power its mobile apps and wasn't publicly open-sourced until three years later.",
    icon: "/logos/graphql.svg",
    aspect: 0.889,
    gitLink: "https://github.com/graphql/graphql-spec",
  },
  {
    name: "GreenSock",
    industry: "Animation library",
    founded: 2008,
    funFact:
      "GreenSock's GSAP animation engine is used so heavily in advertising and awwwards-winning sites that it's often called the industry standard for web animation.",
    icon: "/logos/greensock.svg",
    aspect: 0.862,
    gitLink: "https://github.com/greensock/GSAP",
  },
  {
    name: "Grunt",
    industry: "Task runner",
    founded: 2012,
    funFact:
      "Grunt was one of the first JavaScript task runners to popularize configuration-over-code build pipelines, before Gulp and npm scripts took over.",
    icon: "/logos/grunt.svg",
    aspect: 0.744,
    gitLink: "https://github.com/gruntjs/grunt",
  },
  {
    name: "Gulp",
    industry: "Task runner",
    founded: 2013,
    funFact:
      "Gulp processes files through in-memory streams rather than writing temporary files to disk, which made it noticeably faster than Grunt at the time.",
    icon: "/logos/gulp.svg",
    aspect: 0.452,
    gitLink: "https://github.com/gulpjs/gulp",
  },
  {
    name: "Handlebars",
    industry: "Templating engine",
    founded: 2010,
    funFact:
      "Handlebars extends Mustache's 'logic-less' templates with helpers and block expressions, trading some of that purity for practicality.",
    icon: "/logos/handlebars.svg",
    aspect: 4.129,
    gitLink: "https://github.com/handlebars-lang/handlebars.js",
  },
  {
    name: "Headless UI",
    industry: "UI component library",
    founded: 2020,
    funFact:
      "Headless UI ships components with zero built-in styles at all, designed specifically to pair with Tailwind CSS for full visual control.",
    icon: "/logos/headlessui.svg",
    aspect: 1,
    gitLink: "https://github.com/tailwindlabs/headlessui",
  },
  {
    name: "Hibernate",
    industry: "Java ORM",
    founded: 2001,
    funFact:
      "Hibernate was created by Gavin King partly out of frustration with EJB 2's entity beans, and its ideas went on to shape the Java Persistence API standard itself.",
    icon: "/logos/hibernate.svg",
    aspect: 0.959,
    gitLink: "https://github.com/hibernate/hibernate-orm",
  },
  {
    name: "Highcharts",
    industry: "Charting library",
    founded: 2009,
    funFact:
      "Highcharts was created by Norwegian developer Torstein Hønsi after he couldn't find a charting library that met his own standards for a personal project.",
    icon: "/logos/highcharts.svg",
    aspect: 1.053,
    gitLink: "https://github.com/highcharts/highcharts",
  },
  {
    name: "Hono",
    industry: "Web framework",
    founded: 2021,
    funFact:
      "Hono's name means 'flame' in Japanese, chosen by creator Yusuke Wada to reflect its focus on being fast and lightweight across any JavaScript runtime.",
    icon: "/logos/hono.svg",
    aspect: 0.776,
    gitLink: "https://github.com/honojs/hono",
  },
  {
    name: "htmx",
    industry: "Hypermedia library",
    founded: 2020,
    funFact:
      "htmx grew out of an earlier jQuery-based library called intercooler.js, rewritten from scratch to let plain HTML attributes trigger AJAX, WebSockets, and more.",
    icon: "/logos/htmx.svg",
    aspect: 1.524,
    gitLink: "https://github.com/bigskysoftware/htmx",
  },
  {
    name: "i18next",
    industry: "Internationalization framework",
    founded: 2011,
    funFact:
      "i18next was designed to work identically across the browser, Node.js, and mobile, so the same translation logic can be shared everywhere.",
    icon: "/logos/i18next.svg",
    aspect: 1,
    gitLink: "https://github.com/i18next/i18next",
  },
  {
    name: "Inferno",
    industry: "JavaScript library",
    founded: 2016,
    funFact:
      "Inferno was built by Dominic Gannaway with a laser focus on raw rendering speed, at one point benchmarking as the fastest of all major virtual DOM libraries.",
    icon: "/logos/inferno.svg",
    aspect: 0.962,
    gitLink: "https://github.com/infernojs/inferno",
  },
  {
    name: "Ionic",
    industry: "Mobile app framework",
    founded: 2013,
    funFact:
      "Ionic originally targeted Angular exclusively before rebuilding its component library on web standards so it could support React and Vue too.",
    icon: "/logos/ionic.svg",
    aspect: 1,
    gitLink: "https://github.com/ionic-team/ionic-framework",
  },
  {
    name: "Jasmine",
    industry: "Testing framework",
    founded: 2010,
    funFact:
      "Jasmine was designed to need no DOM and no other JavaScript frameworks at all, making it runnable in virtually any environment.",
    icon: "/logos/jasmine.svg",
    aspect: 1.004,
    gitLink: "https://github.com/jasmine/jasmine",
  },
  {
    name: "Jest",
    industry: "Testing framework",
    founded: 2011,
    funFact:
      "Jest was originally built at Facebook to test JavaScript at scale and popularized snapshot testing as a way to catch unintended UI changes.",
    icon: "/logos/jest.svg",
    aspect: 0.905,
    gitLink: "https://github.com/jestjs/jest",
  },
  {
    name: "Kafka",
    industry: "Event streaming platform",
    founded: 2011,
    funFact:
      "Kafka was built at LinkedIn and named by co-creator Jay Kreps after the writer Franz Kafka, simply because he liked his work.",
    icon: "/logos/kafka.svg",
    aspect: 0.62,
    gitLink: "https://github.com/apache/kafka",
  },
  {
    name: "Karma",
    industry: "Test runner",
    founded: 2012,
    funFact:
      "Karma was originally called Testacular, and was built by the AngularJS team to run tests across real browsers instead of a simulated environment.",
    icon: "/logos/karma.svg",
    aspect: 1.293,
    gitLink: "https://github.com/karma-runner/karma",
  },
  {
    name: "Kibana",
    industry: "Data visualization",
    founded: 2013,
    funFact:
      "Kibana was created as a side project to visualize logs stored in Elasticsearch before becoming an official part of Elastic's product line.",
    icon: "/logos/kibana.svg",
    aspect: 0.78,
    gitLink: "https://github.com/elastic/kibana",
  },
  {
    name: "Kong",
    industry: "API gateway",
    founded: 2015,
    funFact:
      "Kong grew out of Mashape's internal API gateway, built to manage traffic across the thousands of APIs listed on its own marketplace.",
    icon: "/logos/kong.svg",
    aspect: 1.138,
    gitLink: "https://github.com/Kong/kong",
  },
  {
    name: "Kubernetes",
    industry: "Container orchestration",
    founded: 2014,
    funFact:
      "Kubernetes is based on Borg, the internal cluster manager Google had used for over a decade to run its own production workloads.",
    icon: "/logos/kubernetes.svg",
    aspect: 1.028,
    gitLink: "https://github.com/kubernetes/kubernetes",
  },
  {
    name: "Laravel",
    industry: "PHP framework",
    founded: 2011,
    funFact:
      "Laravel was created by Taylor Otwell as a more expressive alternative to CodeIgniter, which lacked built-in support for things like authentication.",
    icon: "/logos/laravel.svg",
    aspect: 0.97,
    gitLink: "https://github.com/laravel/laravel",
  },
  {
    name: "Leaflet",
    industry: "Mapping library",
    founded: 2011,
    funFact:
      "Leaflet was built by Ukrainian developer Vladimir Agafonkin with a deliberate focus on staying small and simple rather than feature-complete.",
    icon: "/logos/leaflet.svg",
    aspect: 1,
    gitLink: "https://github.com/Leaflet/Leaflet",
  },
  {
    name: "Lit",
    industry: "Web components library",
    founded: 2019,
    funFact:
      "Lit is Google's successor to Polymer, built directly on native browser Web Components standards instead of a custom component model.",
    icon: "/logos/lit.svg",
    aspect: 0.8,
    gitLink: "https://github.com/lit/lit",
  },
  {
    name: "Mantine",
    industry: "UI component library",
    founded: 2021,
    funFact:
      "Mantine ships over 100 customizable components along with more than 50 hooks, built with a strong focus on accessibility out of the box.",
    icon: "/logos/mantine.svg",
    aspect: 0.992,
    gitLink: "https://github.com/mantinedev/mantine",
  },
  {
    name: "MariaDB",
    industry: "Relational database",
    founded: 2009,
    funFact:
      "MariaDB was forked from MySQL by its original creator Michael Widenius the day Oracle acquired Sun, out of concern for MySQL's future as open source.",
    icon: "/logos/mariadb.svg",
    aspect: 1.506,
    gitLink: "https://github.com/MariaDB/server",
  },
  {
    name: "Marko",
    industry: "JavaScript framework",
    founded: 2014,
    funFact: "Marko was built at eBay specifically to speed up server-side rendering for its own high-traffic commerce pages.",
    icon: "/logos/marko.svg",
    aspect: 1.816,
    gitLink: "https://github.com/marko-js/marko",
  },
  {
    name: "Meteor",
    industry: "Full-stack JavaScript framework",
    founded: 2012,
    funFact:
      "Meteor pioneered 'full-stack reactivity', automatically syncing data changes from the server database straight through to the browser UI in real time.",
    icon: "/logos/meteor.svg",
    aspect: 1.02,
    gitLink: "https://github.com/meteor/meteor",
  },
  {
    name: "Mock Service Worker",
    industry: "API mocking library",
    founded: 2019,
    funFact:
      "Mock Service Worker intercepts requests at the network level using the Service Worker API, so mocked responses look identical to real network traffic.",
    icon: "/logos/msw.svg",
    aspect: 1,
    gitLink: "https://github.com/mswjs/msw",
  },
  {
    name: "MUI",
    industry: "UI component library",
    founded: 2014,
    funFact:
      "MUI (originally Material-UI) began as one of the first React libraries to fully implement Google's then-new Material Design guidelines.",
    icon: "/logos/material-ui.svg",
    aspect: 1.153,
    gitLink: "https://github.com/mui/material-ui",
  },
  {
    name: "MySQL",
    industry: "Relational database",
    founded: 1995,
    funFact: "MySQL is named after co-founder Michael Widenius's daughter, My, combined with the SQL query language.",
    icon: "/logos/mysql.svg",
    aspect: 1.016,
    gitLink: "https://github.com/mysql/mysql-server",
  },
  {
    name: "NestJS",
    industry: "Node.js framework",
    founded: 2017,
    funFact:
      "NestJS borrows its architecture heavily from Angular, bringing decorators, dependency injection, and modules to server-side Node.js applications.",
    icon: "/logos/nestjs.svg",
    aspect: 1.004,
    gitLink: "https://github.com/nestjs/nest",
  },
  {
    name: "Netlify",
    industry: "Web hosting platform",
    founded: 2014,
    funFact:
      "Netlify is widely credited with popularizing the term 'Jamstack' to describe sites built from pre-rendered markup, APIs, and JavaScript.",
    icon: "/logos/netlify.svg",
    aspect: 1.133,
    gitLink: "https://github.com/netlify",
  },
  {
    name: "New Relic",
    industry: "Observability platform",
    founded: 2008,
    funFact:
      "New Relic was founded by Lew Cirne, who had previously built and sold an earlier application performance monitoring company called Wily Technology.",
    icon: "/logos/new-relic.svg",
    aspect: 0.865,
    gitLink: "https://github.com/newrelic",
  },
  {
    name: "Next.js",
    industry: "React framework",
    founded: 2016,
    funFact:
      "Next.js was created by Vercel (then called Zeit) to give React server-side rendering and routing out of the box without hand-rolled configuration.",
    icon: "/logos/nextjs.svg",
    aspect: 1,
    gitLink: "https://github.com/vercel/next.js",
  },
  {
    name: "NGINX",
    industry: "Web server",
    founded: 2004,
    funFact:
      "NGINX was written by Igor Sysoev specifically to solve the C10k problem: handling ten thousand concurrent connections efficiently on a single server.",
    icon: "/logos/nginx.svg",
    aspect: 0.88,
    gitLink: "https://github.com/nginx/nginx",
  },
  {
    name: "npm",
    industry: "Package manager",
    founded: 2010,
    funFact:
      "npm was created by Isaac Z. Schafer and shipped bundled with Node.js, quickly becoming the largest software registry in the world by package count.",
    icon: "/logos/npmjs.svg",
    aspect: 1,
    gitLink: "https://github.com/npm/cli",
  },
  {
    name: "nuqs",
    industry: "URL state library",
    founded: 2020,
    funFact:
      "nuqs (pronounced 'nukes') keeps React state type-safe and synced directly to the URL query string, so state survives refreshes and is shareable by link.",
    icon: "/logos/nuqs.svg",
    aspect: 1,
    gitLink: "https://github.com/47ng/nuqs",
  },
  {
    name: "Nuxt",
    industry: "Vue framework",
    founded: 2016,
    funFact: "Nuxt was directly inspired by Next.js, bringing the same convention-driven server-rendering approach to the Vue ecosystem.",
    icon: "/logos/nuxt.svg",
    aspect: 1.524,
    gitLink: "https://github.com/nuxt/nuxt",
  },
  {
    name: "OpenAPI",
    industry: "API specification",
    founded: 2011,
    funFact:
      "OpenAPI began life as the Swagger Specification, created by Tony Tam, before being donated to the Linux Foundation and renamed in 2016.",
    icon: "/logos/openapi.svg",
    aspect: 1,
    gitLink: "https://github.com/OAI/OpenAPI-Specification",
  },
  {
    name: "Oxc",
    industry: "JavaScript toolchain",
    founded: 2022,
    funFact:
      "Oxc is short for 'Oxidation Compiler' and rewrites the entire JavaScript toolchain — parser, linter, and transformer — in Rust for order-of-magnitude speedups.",
    icon: "/logos/oxc.svg",
    aspect: 1.631,
    gitLink: "https://github.com/oxc-project/oxc",
  },
  {
    name: "Panda CSS",
    industry: "CSS-in-JS framework",
    founded: 2023,
    funFact:
      "Panda CSS was built by Chakra UI's creator Segun Adebayo to statically extract styles at build time instead of generating them at runtime.",
    icon: "/logos/pandacss.svg",
    aspect: 0.988,
    gitLink: "https://github.com/chakra-ui/panda",
  },
  {
    name: "Parcel",
    industry: "JavaScript bundler",
    founded: 2017,
    funFact:
      "Parcel was designed around zero-configuration bundling, automatically figuring out how to build a project without a config file at all.",
    icon: "/logos/parcel.svg",
    aspect: 1.326,
    gitLink: "https://github.com/parcel-bundler/parcel",
  },
  {
    name: "Partytown",
    industry: "Web performance library",
    founded: 2021,
    funFact:
      "Partytown moves resource-heavy third-party scripts like analytics tags off the main thread and into a web worker, keeping pages responsive.",
    icon: "/logos/partytown.svg",
    aspect: 0.955,
    gitLink: "https://github.com/BuilderIO/partytown",
  },
  {
    name: "Phoenix",
    industry: "Elixir web framework",
    founded: 2014,
    funFact:
      "Phoenix's LiveView feature lets developers build rich, real-time interactive UIs by pushing HTML diffs over a WebSocket instead of writing client-side JavaScript.",
    icon: "/logos/phoenix.svg",
    aspect: 1.463,
    gitLink: "https://github.com/phoenixframework/phoenix",
  },
  {
    name: "Pico CSS",
    industry: "CSS framework",
    founded: 2019,
    funFact: "Pico CSS styles plain semantic HTML directly, so a page looks reasonably designed with almost no extra class names required.",
    icon: "/logos/picocss.svg",
    aspect: 1,
    gitLink: "https://github.com/picocss/pico",
  },
  {
    name: "Pinia",
    industry: "State management library",
    founded: 2019,
    funFact:
      "Pinia started as an experiment testing what a Vue 3 store API could look like, and was later adopted as Vue's official replacement for Vuex.",
    icon: "/logos/pinia.svg",
    aspect: 0.773,
    gitLink: "https://github.com/vuejs/pinia",
  },
  {
    name: "Playwright",
    industry: "End-to-end testing",
    founded: 2020,
    funFact: "Playwright was built by many of the same engineers who created Puppeteer at Google, after they moved to Microsoft.",
    icon: "/logos/playwright.svg",
    aspect: 1.333,
    gitLink: "https://github.com/microsoft/playwright",
  },
  {
    name: "Polymer",
    industry: "Web components library",
    founded: 2015,
    funFact:
      "Polymer was Google's early effort to make Web Components practical to use, years before the standard had full native browser support.",
    icon: "/logos/polymer.svg",
    aspect: 1.438,
    gitLink: "https://github.com/Polymer/polymer",
  },
  {
    name: "PostCSS",
    industry: "CSS transformation tool",
    founded: 2013,
    funFact:
      "PostCSS doesn't do anything to CSS by itself; virtually all of its power, including features like Autoprefixer, comes from its plugin ecosystem.",
    icon: "/logos/postcss.svg",
    aspect: 1,
    gitLink: "https://github.com/postcss/postcss",
  },
  {
    name: "PostgreSQL",
    industry: "Relational database",
    founded: 1996,
    funFact:
      "PostgreSQL traces its roots to the POSTGRES project at UC Berkeley in the 1980s, led by database pioneer Michael Stonebraker.",
    icon: "/logos/postgresql.svg",
    aspect: 0.97,
    gitLink: "https://github.com/postgres/postgres",
  },
  {
    name: "Postman",
    industry: "API development platform",
    founded: 2014,
    funFact:
      "Postman began as a side-project Chrome extension built by Abhinav Asthana to make testing APIs easier than using raw curl commands.",
    icon: "/logos/postman.svg",
    aspect: 1,
    gitLink: "https://github.com/postmanlabs",
  },
  {
    name: "PouchDB",
    industry: "JavaScript database",
    founded: 2012,
    funFact:
      "PouchDB mirrors CouchDB's API in the browser and can sync bidirectionally with a CouchDB server, making offline-first apps far easier to build.",
    icon: "/logos/pouchdb.svg",
    aspect: 0.776,
    gitLink: "https://github.com/pouchdb/pouchdb",
  },
  {
    name: "PowerSync",
    industry: "Offline sync engine",
    founded: 2022,
    funFact:
      "PowerSync was spun out of JourneyApps, whose offline-first mobile platform had already been syncing data for enterprise field teams for over a decade.",
    icon: "/logos/powersync.svg",
    aspect: 1.333,
    gitLink: "https://github.com/powersync-ja/powersync-js",
  },
  {
    name: "Prettier",
    industry: "Code formatter",
    founded: 2017,
    funFact:
      "Prettier deliberately offers very few configuration options, reprinting code from scratch according to its own rules to end debates over formatting style.",
    icon: "/logos/prettier.svg",
    aspect: 1,
    gitLink: "https://github.com/prettier/prettier",
  },
  {
    name: "Prisma",
    industry: "TypeScript ORM",
    founded: 2016,
    funFact:
      "Prisma originally shipped as a GraphQL-focused database layer before a full rewrite turned it into the type-safe ORM most developers know today.",
    icon: "/logos/prisma.svg",
    aspect: 0.826,
    gitLink: "https://github.com/prisma/prisma",
  },
  {
    name: "Qwik",
    industry: "JavaScript framework",
    founded: 2021,
    funFact:
      "Qwik was created by Angular co-creator Miško Hevery around the idea of 'resumability', shipping almost no JavaScript until a user actually interacts with the page.",
    icon: "/logos/qwik.svg",
    aspect: 0.941,
    gitLink: "https://github.com/QwikDev/qwik",
  },
  {
    name: "RabbitMQ",
    industry: "Message broker",
    founded: 2007,
    funFact:
      "RabbitMQ implements the AMQP messaging protocol and was one of the first open-source message brokers built specifically around that open standard.",
    icon: "/logos/rabbitmq.svg",
    aspect: 0.996,
    gitLink: "https://github.com/rabbitmq/rabbitmq-server",
  },
  {
    name: "Railway",
    industry: "Deployment platform",
    founded: 2020,
    funFact:
      "Railway lets developers deploy an entire app, including databases and background services, by simply pointing it at a GitHub repository.",
    icon: "/logos/railway.svg",
    aspect: 1,
    gitLink: "https://github.com/railwayapp",
  },
  {
    name: "Ramda",
    industry: "Functional programming library",
    founded: 2013,
    funFact:
      "Ramda automatically curries every one of its functions and always puts the data argument last, making it easy to build pipelines of composed functions.",
    icon: "/logos/ramda.svg",
    aspect: 0.837,
    gitLink: "https://github.com/ramda/ramda",
  },
  {
    name: "Recoil",
    industry: "State management library",
    founded: 2020,
    funFact:
      "Recoil was built and open-sourced by Facebook to solve state-sharing problems its own engineers kept running into with plain React Context.",
    icon: "/logos/recoil.svg",
    aspect: 0.43,
    gitLink: "https://github.com/facebookexperimental/Recoil",
  },
  {
    name: "Redis",
    industry: "In-memory database",
    founded: 2009,
    funFact:
      "Redis was created by Salvatore Sanfilippo to speed up a real-time web analytics startup he was building, and its name is short for 'Remote Dictionary Server'.",
    icon: "/logos/redis.svg",
    aspect: 1.164,
    gitLink: "https://github.com/redis/redis",
  },
  {
    name: "Redux",
    industry: "State management library",
    founded: 2015,
    funFact:
      "Redux was created by Dan Abramov for a conference talk and was directly inspired by Facebook's Flux pattern combined with the functional reducer style of Elm.",
    icon: "/logos/redux.svg",
    aspect: 1.049,
    gitLink: "https://github.com/reduxjs/redux",
  },
  {
    name: "RedwoodJS",
    industry: "Full-stack JavaScript framework",
    founded: 2020,
    funFact:
      "RedwoodJS was created by Tom Preston-Werner, the co-founder of GitHub, aiming to bring Rails-like conventions to full-stack JavaScript apps.",
    icon: "/logos/redwoodjs.svg",
    aspect: 0.924,
    gitLink: "https://github.com/redwoodjs/redwood",
  },
  {
    name: "Relay",
    industry: "GraphQL client",
    founded: 2015,
    funFact:
      "Relay was released by Facebook alongside GraphQL itself and pushed data-fetching logic down into individual React components rather than top-level pages.",
    icon: "/logos/relay.svg",
    aspect: 1.695,
    gitLink: "https://github.com/facebook/relay",
  },
  {
    name: "Remix",
    industry: "React framework",
    founded: 2021,
    funFact: "Remix was built by Ryan Florence and Michael Jackson, the same duo behind React Router, and was later acquired by Shopify.",
    icon: "/logos/remix.svg",
    aspect: 0.862,
    gitLink: "https://github.com/remix-run/remix",
  },
  {
    name: "Remotion",
    industry: "Video creation library",
    founded: 2021,
    funFact:
      "Remotion lets developers create videos entirely in React, rendering each frame as a component so animations can use real code instead of a timeline editor.",
    icon: "/logos/remotion.svg",
    aspect: 1,
    gitLink: "https://github.com/remotion-dev/remotion",
  },
  {
    name: "Renovate",
    industry: "Dependency automation",
    founded: 2017,
    funFact:
      "Renovate was created as an independent open-source project by Rhys Arkins before being acquired by WhiteSource (now Mend) in 2019.",
    icon: "/logos/renovate.svg",
    aspect: 1,
    gitLink: "https://github.com/renovatebot/renovate",
  },
  {
    name: "Reveal.js",
    industry: "Presentation framework",
    founded: 2011,
    funFact:
      "Reveal.js turns a plain HTML file into a full slide deck in the browser, including built-in support for 3D transitions and Markdown slides.",
    icon: "/logos/reveal-js.svg",
    aspect: 1,
    gitLink: "https://github.com/hakimel/reveal.js",
  },
  {
    name: "Rolldown",
    industry: "JavaScript bundler",
    founded: 2024,
    funFact:
      "Rolldown is a Rust rewrite of Rollup built by Vue creator Evan You's company VoidZero, designed to become the new bundling core underneath Vite.",
    icon: "/logos/rolldown.svg",
    aspect: 1.631,
    gitLink: "https://github.com/rolldown/rolldown",
  },
  {
    name: "Rollup",
    industry: "JavaScript bundler",
    founded: 2015,
    funFact:
      "Rollup was created by Rich Harris and was one of the first bundlers built around ES modules, popularizing 'tree-shaking' to strip out unused code.",
    icon: "/logos/rollupjs.svg",
    aspect: 0.764,
    gitLink: "https://github.com/rollup/rollup",
  },
  {
    name: "Rsbuild",
    industry: "Build tool",
    founded: 2024,
    funFact:
      "Rsbuild is built by ByteDance on top of their Rspack bundler, packaging it with sensible defaults so teams don't have to configure it from scratch.",
    icon: "/logos/rsbuild.svg",
    aspect: 1.066,
    gitLink: "https://github.com/web-infra-dev/rsbuild",
  },
  {
    name: "RxJS",
    industry: "Reactive programming library",
    founded: 2010,
    funFact:
      "RxJS brings the ReactiveX pattern, originally developed at Microsoft for .NET, into JavaScript by modeling asynchronous events as composable streams.",
    icon: "/logos/rxjs.svg",
    aspect: 0.965,
    gitLink: "https://github.com/ReactiveX/rxjs",
  },
  {
    name: "Sails.js",
    industry: "Node.js MVC framework",
    founded: 2012,
    funFact:
      "Sails.js was designed to feel familiar to Ruby on Rails developers, adding conventions like blueprint REST APIs auto-generated from your models.",
    icon: "/logos/sails.svg",
    aspect: 1,
    gitLink: "https://github.com/balderdashy/sails",
  },
  {
    name: "Semantic UI",
    industry: "UI component library",
    founded: 2013,
    funFact:
      "Semantic UI was built around human-readable class names like 'ui button' instead of terse utility abbreviations, aiming for markup that reads like English.",
    icon: "/logos/semantic-ui.svg",
    aspect: 1,
    gitLink: "https://github.com/Semantic-Org/Semantic-UI",
  },
  {
    name: "Sentry",
    industry: "Error tracking platform",
    founded: 2008,
    funFact:
      "Sentry began as a small internal tool at Disqus for tracking Django errors before its creators spun it out into its own company.",
    icon: "/logos/sentry.svg",
    aspect: 1.128,
    gitLink: "https://github.com/getsentry/sentry",
  },
  {
    name: "Sequelize",
    industry: "Node.js ORM",
    founded: 2010,
    funFact:
      "Sequelize supports Postgres, MySQL, MariaDB, SQLite, and SQL Server through a single unified API, letting projects swap databases with minimal code changes.",
    icon: "/logos/sequelize.svg",
    aspect: 1,
    gitLink: "https://github.com/sequelize/sequelize",
  },
  {
    name: "shadcn/ui",
    industry: "UI component library",
    founded: 2023,
    funFact:
      "shadcn/ui isn't installed as a package at all — its CLI copies component source code directly into your project so you can freely edit every line.",
    icon: "/logos/shadcn-ui.svg",
    aspect: 1,
    gitLink: "https://github.com/shadcn-ui/ui",
  },
  {
    name: "Slidev",
    industry: "Presentation framework",
    founded: 2020,
    funFact:
      "Slidev lets developers write slide decks in Markdown while embedding live, interactive Vue components directly inside a presentation.",
    icon: "/logos/slidev.svg",
    aspect: 1,
    gitLink: "https://github.com/slidevjs/slidev",
  },
  {
    name: "Socket.IO",
    industry: "Realtime library",
    founded: 2010,
    funFact:
      "Socket.IO automatically falls back to HTTP long-polling when WebSockets aren't available, which is a big part of why it took off in the early 2010s.",
    icon: "/logos/socket-io.svg",
    aspect: 1,
    gitLink: "https://github.com/socketio/socket.io",
  },
  {
    name: "SonarCloud",
    industry: "Code quality platform",
    founded: 2016,
    funFact:
      "SonarCloud is the cloud-hosted counterpart to SonarQube, built by SonarSource to run static analysis directly inside CI pipelines.",
    icon: "/logos/sonarcloud.svg",
    aspect: 1.103,
    gitLink: "https://github.com/SonarSource/sonarqube",
  },
  {
    name: "Spring",
    industry: "Java framework",
    founded: 2003,
    funFact:
      "Spring was created by Rod Johnson as a reaction against the complexity of Enterprise JavaBeans, built around simpler dependency injection instead.",
    icon: "/logos/spring.svg",
    aspect: 1,
    gitLink: "https://github.com/spring-projects/spring-framework",
  },
  {
    name: "Stately",
    industry: "State machine visualizer",
    founded: 2021,
    funFact:
      "Stately was founded by David Khourshid, creator of the XState library, to give state machines a visual editor instead of only code.",
    icon: "/logos/stately.svg",
    aspect: 0.837,
    gitLink: "https://github.com/statelyai",
  },
  {
    name: "Stencil",
    industry: "Web components compiler",
    founded: 2017,
    funFact:
      "Stencil was built by the Ionic team to compile familiar JSX and TypeScript components down into standards-based Web Components with no runtime framework required.",
    icon: "/logos/stencil.svg",
    aspect: 1.299,
    gitLink: "https://github.com/ionic-team/stencil",
  },
  {
    name: "Storybook",
    industry: "UI development environment",
    founded: 2016,
    funFact:
      "Storybook lets developers build and test UI components entirely in isolation, outside of the actual application they'll eventually live in.",
    icon: "/logos/storybook.svg",
    aspect: 0.803,
    gitLink: "https://github.com/storybookjs/storybook",
  },
  {
    name: "Supabase",
    industry: "Backend-as-a-service",
    founded: 2020,
    funFact:
      "Supabase was built explicitly as an open-source alternative to Firebase, but on top of PostgreSQL instead of a proprietary NoSQL database.",
    icon: "/logos/supabase.svg",
    aspect: 0.973,
    gitLink: "https://github.com/supabase/supabase",
  },
  {
    name: "Svelte",
    industry: "JavaScript framework",
    founded: 2016,
    funFact:
      "Svelte does its heavy lifting at build time, compiling components into vanilla JavaScript rather than shipping a framework runtime to the browser.",
    icon: "/logos/svelte.svg",
    aspect: 0.831,
    gitLink: "https://github.com/sveltejs/svelte",
  },
  {
    name: "Symfony",
    industry: "PHP framework",
    founded: 2005,
    funFact: "Symfony's reusable components ended up powering large parts of other major PHP projects, including Laravel and Drupal.",
    icon: "/logos/symfony.svg",
    aspect: 0.996,
    gitLink: "https://github.com/symfony/symfony",
  },
  {
    name: "Tailwind CSS",
    industry: "Utility-first CSS framework",
    founded: 2017,
    funFact:
      "Tailwind CSS was created by Adam Wathan after he kept rebuilding the same set of utility classes across different client projects.",
    icon: "/logos/tailwindcss.svg",
    aspect: 1.662,
    gitLink: "https://github.com/tailwindlabs/tailwindcss",
  },
  {
    name: "Terraform",
    industry: "Infrastructure as code",
    founded: 2014,
    funFact:
      "Terraform lets teams describe cloud infrastructure across many different providers in one declarative language, then plans changes before applying them.",
    icon: "/logos/terraform.svg",
    aspect: 0.88,
    gitLink: "https://github.com/hashicorp/terraform",
  },
  {
    name: "Testing Library",
    industry: "Testing utility",
    founded: 2018,
    funFact:
      "Testing Library was built by Kent C. Dodds around one guiding principle: tests should interact with an app the same way a real user would.",
    icon: "/logos/testing-library.svg",
    aspect: 1,
    gitLink: "https://github.com/testing-library/testing-library-docs",
  },
  {
    name: "Three.js",
    industry: "3D graphics library",
    founded: 2010,
    funFact:
      "Three.js was created by Ricardo Cabello, known online as Mr.doom, to make WebGL's notoriously low-level API usable without writing raw shader code.",
    icon: "/logos/threejs.svg",
    aspect: 0.988,
    gitLink: "https://github.com/mrdoob/three.js",
  },
  {
    name: "Thymeleaf",
    industry: "Java templating engine",
    founded: 2011,
    funFact:
      "Thymeleaf templates are valid HTML that can be opened and previewed directly in a browser, even before the templating engine ever processes them.",
    icon: "/logos/thymeleaf.svg",
    aspect: 0.996,
    gitLink: "https://github.com/thymeleaf/thymeleaf",
  },
  {
    name: "Turbopack",
    industry: "JavaScript bundler",
    founded: 2022,
    funFact:
      "Turbopack was announced by Webpack's original creator Tobias Koppers after he joined Vercel to build its Rust-based successor.",
    icon: "/logos/turbopack.svg",
    aspect: 0.874,
    gitLink: "https://github.com/vercel/turborepo",
  },
  {
    name: "Turborepo",
    industry: "Monorepo build system",
    founded: 2021,
    funFact:
      "Turborepo caches the output of every task so thoroughly that re-running a build with no changes can complete in milliseconds by replaying cached results.",
    icon: "/logos/turborepo.svg",
    aspect: 0.805,
    gitLink: "https://github.com/vercel/turborepo",
  },
  {
    name: "Twilio",
    industry: "Communications platform",
    founded: 2008,
    funFact:
      "Twilio let developers add phone calls and SMS to any application with a simple API call, at a time when telecom infrastructure was normally locked behind carriers.",
    icon: "/logos/twilio.svg",
    aspect: 1,
    gitLink: "https://github.com/twilio",
  },
  {
    name: "UnoCSS",
    industry: "Atomic CSS engine",
    founded: 2021,
    funFact:
      "UnoCSS has no core utilities of its own by default; instead it's an engine that generates styles on demand from whatever preset rules you load, including a Tailwind-compatible one.",
    icon: "/logos/unocss.svg",
    aspect: 1,
    gitLink: "https://github.com/unocss/unocss",
  },
  {
    name: "Valibot",
    industry: "Schema validation library",
    founded: 2023,
    funFact:
      "Valibot began as part of creator Fabian Hiller's university thesis and was designed around a modular API so unused validators can be tree-shaken out entirely.",
    icon: "/logos/valibot.svg",
    aspect: 1,
    gitLink: "https://github.com/fabian-hiller/valibot",
  },
  {
    name: "Vite",
    industry: "Build tool",
    founded: 2020,
    funFact:
      "Vite is French for 'fast' and was created by Vue's Evan You, serving source files over native ES modules in development to skip bundling entirely.",
    icon: "/logos/vite.svg",
    aspect: 1.631,
    gitLink: "https://github.com/vitejs/vite",
  },
  {
    name: "Vitest",
    industry: "Testing framework",
    founded: 2021,
    funFact:
      "Vitest reuses Vite's own configuration and plugin pipeline for running tests, so projects already using Vite need almost no extra test setup.",
    icon: "/logos/vitest.svg",
    aspect: 1.094,
    gitLink: "https://github.com/vitest-dev/vitest",
  },
  {
    name: "Windi CSS",
    industry: "Utility-first CSS framework",
    founded: 2020,
    funFact:
      "Windi CSS generated utility classes on demand instead of shipping a giant precompiled stylesheet, an idea its own maintainers later carried into UnoCSS after sunsetting the project.",
    icon: "/logos/windi-css.svg",
    aspect: 0.918,
    gitLink: "https://github.com/windicss/windicss",
  },
  {
    name: "Yarn",
    industry: "Package manager",
    founded: 2016,
    funFact:
      "Yarn was released by Facebook to fix npm's inconsistent installs at the time, introducing a lockfile that guaranteed the exact same dependency tree on every machine.",
    icon: "/logos/yarn.svg",
    aspect: 1,
    gitLink: "https://github.com/yarnpkg/berry",
  },
  {
    name: "AdonisJS",
    industry: "Node.js framework",
    founded: 2015,
    funFact:
      "AdonisJS was created by Harminder Virk and was one of the first Node.js frameworks to ship a full MVC structure with a built-in ORM, drawing heavily on Laravel's conventions.",
    icon: "/logos/adonisjs.svg",
    aspect: 1,
    gitLink: "https://github.com/adonisjs/core",
  },
  {
    name: "Angular",
    industry: "JavaScript framework",
    founded: 2016,
    funFact:
      "Angular was a complete rewrite of AngularJS released in September 2016, swapping JavaScript controllers for TypeScript components with no backward compatibility.",
    icon: "/logos/angular.svg",
    aspect: 1,
    gitLink: "https://github.com/angular/angular",
  },
  {
    name: "Ansible",
    industry: "IT automation tool",
    founded: 2012,
    funFact:
      "Ansible is named after the fictional instantaneous communication device from Ursula K. Le Guin's science fiction novels.",
    icon: "/logos/ansible.svg",
    aspect: 1,
    gitLink: "https://github.com/ansible/ansible",
  },
  {
    name: "Ant Design",
    industry: "UI component library",
    founded: 2015,
    funFact:
      "Ant Design was built by Alibaba's UED team and takes its name from the idea of many small, disciplined components working together like a colony of ants.",
    icon: "/logos/antdesign.svg",
    aspect: 1,
    gitLink: "https://github.com/ant-design/ant-design",
  },
  {
    name: "Apache Cassandra",
    industry: "NoSQL database",
    founded: 2008,
    funFact:
      "Cassandra was originally developed at Facebook to power its inbox search feature before being open-sourced in 2008.",
    icon: "/logos/cassandra.svg",
    aspect: 1,
    gitLink: "https://github.com/apache/cassandra",
  },
  {
    name: "Apache CouchDB",
    industry: "NoSQL database",
    founded: 2005,
    funFact:
      "CouchDB was created by former Lotus Notes developer Damien Katz and uses HTTP and JSON natively as its query interface.",
    icon: "/logos/couchdb.svg",
    aspect: 1,
    gitLink: "https://github.com/apache/couchdb",
  },
  {
    name: "Apache Hadoop",
    industry: "Distributed computing framework",
    founded: 2006,
    funFact: "Hadoop is named after co-creator Doug Cutting's son's stuffed yellow elephant toy.",
    icon: "/logos/hadoop.svg",
    aspect: 1,
    gitLink: "https://github.com/apache/hadoop",
  },
  {
    name: "Apollo Client",
    industry: "GraphQL client",
    founded: 2016,
    funFact:
      "Apollo grew out of the Meteor Development Group, which pivoted its entire company focus from the Meteor framework to GraphQL tooling.",
    icon: "/logos/apollographql.svg",
    aspect: 1,
    gitLink: "https://github.com/apollographql/apollo-client",
  },
  {
    name: "Appwrite",
    industry: "Backend-as-a-service",
    founded: 2019,
    funFact:
      "Appwrite was open-sourced by Eldad Fux in 2019 as a self-hosted alternative to Firebase, packaged entirely as Docker microservices.",
    icon: "/logos/appwrite.svg",
    aspect: 1,
    gitLink: "https://github.com/appwrite/appwrite",
  },
  {
    name: "Astro",
    industry: "Web framework",
    founded: 2021,
    funFact:
      "Astro pioneered the 'islands architecture' pattern, shipping zero JavaScript by default and hydrating only the individual components that need interactivity.",
    icon: "/logos/astro.svg",
    aspect: 1,
    gitLink: "https://github.com/withastro/astro",
  },
  {
    name: "Auth.js",
    industry: "Authentication library",
    founded: 2020,
    funFact:
      "Auth.js began life as NextAuth.js, built specifically for Next.js in 2020, before expanding to support other frameworks like SvelteKit and Express and being renamed accordingly.",
    icon: "/logos/auth-js.svg",
    aspect: 0.905,
    gitLink: "https://github.com/nextauthjs/next-auth",
  },
  {
    name: "Auth0",
    industry: "Identity platform",
    founded: 2013,
    funFact:
      "Auth0 was founded by longtime friends Eugenio Pace and Matias Woloski while living 7,000 miles apart in Seattle and Buenos Aires, and was later acquired by Okta for $6.5 billion.",
    icon: "/logos/auth0.svg",
    aspect: 0.898,
    gitLink: "https://github.com/auth0",
  },
  {
    name: "Axios",
    industry: "HTTP client library",
    founded: 2014,
    funFact:
      "Axios was created by Matt Zabriskie and automatically transforms JSON data while working identically in both browsers and Node.js from a single API.",
    icon: "/logos/axios.svg",
    aspect: 1,
    gitLink: "https://github.com/axios/axios",
  },
  {
    name: "Babylon.js",
    industry: "3D graphics library",
    founded: 2013,
    funFact: "Babylon.js was created by Microsoft engineer David Catuhe as a real-time 3D engine built entirely on WebGL.",
    icon: "/logos/babylonjs.svg",
    aspect: 1,
    gitLink: "https://github.com/BabylonJS/Babylon.js",
  },
  {
    name: "Backbone.js",
    industry: "JavaScript library",
    founded: 2010,
    funFact:
      "Backbone.js was created by Jeremy Ashkenas, who also created CoffeeScript, and requires only Underscore.js as its single hard dependency.",
    icon: "/logos/backbonejs.svg",
    aspect: 1,
    gitLink: "https://github.com/jashkenas/backbone",
  },
  {
    name: "Better Auth",
    industry: "Authentication library",
    founded: 2024,
    funFact:
      "Better Auth was launched in 2024 to give TypeScript developers a fully framework-agnostic, self-hosted authentication library built around plugins instead of hosted third-party providers.",
    icon: "/logos/better-auth.svg",
    aspect: 1,
    gitLink: "https://github.com/better-auth/better-auth",
  },
  {
    name: "Bitwarden",
    industry: "Password manager",
    founded: 2016,
    funFact:
      "Bitwarden started as a solo side project by Kyle Spearrin in 2015 after growing dissatisfied with LastPass, and launched publicly in 2016 with a commitment to staying fully open source.",
    icon: "/logos/bitwarden.svg",
    aspect: 0.835,
    gitLink: "https://github.com/bitwarden/server",
  },
  {
    name: "Bootstrap",
    industry: "CSS framework",
    founded: 2011,
    funFact: "Bootstrap was created at Twitter by Mark Otto and Jacob Thornton and was originally called Twitter Blueprint.",
    icon: "/logos/bootstrap.svg",
    aspect: 1,
    gitLink: "https://github.com/twbs/bootstrap",
  },
  {
    name: "Bulma",
    industry: "CSS framework",
    founded: 2016,
    funFact:
      "Bulma is a purely CSS framework with no JavaScript components at all, relying entirely on Flexbox for its layout system.",
    icon: "/logos/bulma.svg",
    aspect: 1,
    gitLink: "https://github.com/jgthms/bulma",
  },
  {
    name: "Bun",
    industry: "JavaScript runtime",
    founded: 2022,
    funFact: "Bun is written in Zig and bundles a runtime, bundler, test runner, and package manager into a single fast binary.",
    icon: "/logos/bun.svg",
    aspect: 1,
    gitLink: "https://github.com/oven-sh/bun",
  },
  {
    name: "Capacitor",
    industry: "Native app runtime",
    founded: 2018,
    funFact:
      "Capacitor was built by the Ionic team as a modern successor to Cordova, giving web apps direct native iOS and Android runtime access.",
    icon: "/logos/capacitor.svg",
    aspect: 1,
    gitLink: "https://github.com/ionic-team/capacitor",
  },
  {
    name: "Clerk",
    industry: "Authentication platform",
    founded: 2019,
    funFact:
      "Clerk was founded in 2019 by brothers Colin and Braden Sidoti and ships prebuilt, fully styled UI components for sign-in and user management.",
    icon: "/logos/clerk.svg",
    aspect: 1,
    gitLink: "https://github.com/clerk/javascript",
  },
  {
    name: "CoffeeScript",
    industry: "Programming language",
    founded: 2009,
    funFact:
      "CoffeeScript was created by Jeremy Ashkenas to compile down to clean, readable JavaScript, popularizing syntax ideas that later influenced ES6.",
    icon: "/logos/coffeescript.svg",
    aspect: 1,
    gitLink: "https://github.com/jashkenas/coffeescript",
  },
  {
    name: "Deno",
    industry: "JavaScript runtime",
    founded: 2018,
    funFact:
      "Deno was created by Ryan Dahl, the original creator of Node.js, partly to fix design decisions he outlined regretting in a talk called '10 Things I Regret About Node.js'.",
    icon: "/logos/denojs.svg",
    aspect: 1,
    gitLink: "https://github.com/denoland/deno",
  },
  {
    name: "Drupal",
    industry: "Content management system",
    founded: 2001,
    funFact:
      "Drupal began as a message board for founder Dries Buytaert and his friends, and takes its name from the Dutch word 'druppel', meaning 'drop'.",
    icon: "/logos/drupal.svg",
    aspect: 1,
    gitLink: "https://github.com/drupal/drupal",
  },
  {
    name: "DuckDB",
    industry: "Analytical database",
    founded: 2019,
    funFact:
      "DuckDB is an in-process analytical database often described as 'SQLite for analytics', designed to run complex queries directly inside an application with no separate server.",
    icon: "/logos/duckdb.svg",
    aspect: 1,
    gitLink: "https://github.com/duckdb/duckdb",
  },
  {
    name: "DynamoDB",
    industry: "NoSQL database",
    founded: 2012,
    funFact:
      "DynamoDB grew out of a 2007 Amazon whitepaper describing the original internal Dynamo system, before being rebuilt and launched as a fully managed public service in 2012.",
    icon: "/logos/dynamodb.svg",
    aspect: 1,
    gitLink: "https://github.com/aws",
  },
  {
    name: "Electron",
    industry: "Desktop app framework",
    founded: 2013,
    funFact:
      "Electron was created at GitHub to build the Atom text editor, combining Chromium and Node.js into a single desktop app runtime.",
    icon: "/logos/electron.svg",
    aspect: 1,
    gitLink: "https://github.com/electron/electron",
  },
  {
    name: "Elixir",
    industry: "Programming language",
    founded: 2012,
    funFact:
      "Elixir was created by José Valim, a former Ruby on Rails core team member, to bring Erlang's concurrency and fault-tolerance to a more approachable syntax.",
    icon: "/logos/elixir.svg",
    aspect: 1,
    gitLink: "https://github.com/elixir-lang/elixir",
  },
  {
    name: "Elm",
    industry: "Programming language",
    founded: 2012,
    funFact:
      "Elm was created by Evan Czaplicki as his senior thesis project at Harvard, aiming to bring the reliability of functional programming to front-end web development.",
    icon: "/logos/elm.svg",
    aspect: 1,
    gitLink: "https://github.com/elm/compiler",
  },
  {
    name: "Flask",
    industry: "Python web framework",
    founded: 2010,
    funFact:
      "Flask started as an April Fools' Day joke by creator Armin Ronacher, a lightweight wrapper around Werkzeug and Jinja2, before it became popular enough to develop seriously.",
    icon: "/logos/flask.svg",
    aspect: 1,
    gitLink: "https://github.com/pallets/flask",
  },
  {
    name: "Gatling",
    industry: "Load testing tool",
    founded: 2012,
    funFact:
      "Gatling models virtual users as lightweight Scala actors instead of OS threads, letting a single machine simulate tens of thousands of concurrent users.",
    icon: "/logos/gatling.svg",
    aspect: 1,
    gitLink: "https://github.com/gatling/gatling",
  },
  {
    name: "Git",
    industry: "Version control system",
    founded: 2005,
    funFact:
      "Linus Torvalds wrote the first version of Git in about ten days after a licensing dispute forced the Linux kernel project to abandon its previous tool, BitKeeper.",
    icon: "/logos/git.svg",
    aspect: 1,
    gitLink: "https://github.com/git/git",
  },
  {
    name: "HTML5",
    industry: "Markup language standard",
    founded: 2008,
    funFact:
      "The WHATWG began drafting HTML5 independently in 2004 after browser vendors felt the W3C's XHTML-focused roadmap had stalled, and it wasn't finalized as a full Recommendation until 2014.",
    icon: "/logos/html5.svg",
    aspect: 1,
    gitLink: "https://github.com/whatwg/html",
  },
  {
    name: "Hugo",
    industry: "Static site generator",
    founded: 2013,
    funFact:
      "Hugo is written in Go, and creator Steve Francia (spf13) designed it to regenerate an entire site of thousands of pages in well under a second.",
    icon: "/logos/hugo.svg",
    aspect: 1,
    gitLink: "https://github.com/gohugoio/hugo",
  },
  {
    name: "Inertia.js",
    industry: "Full-stack framework glue",
    founded: 2019,
    funFact:
      "Inertia.js was inspired by Turbolinks and lets developers build single-page apps using classic server-side routing and controllers from frameworks like Laravel and Rails, without building a separate API.",
    icon: "/logos/inertiajs.svg",
    aspect: 1,
    gitLink: "https://github.com/inertiajs/inertia",
  },
  {
    name: "Insomnia",
    industry: "API development platform",
    founded: 2015,
    funFact:
      "Insomnia was built as a solo side project by developer Gregory Schier before Kong Inc. acquired it in 2019 and continued developing it as an open-source alternative to Postman.",
    icon: "/logos/insomnia.svg",
    aspect: 1,
    gitLink: "https://github.com/Kong/insomnia",
  },
  {
    name: "Java",
    industry: "Programming language",
    founded: 1995,
    funFact:
      "Java was originally called Oak, named by creator James Gosling after an oak tree outside his office, before being renamed for trademark reasons ahead of its 1995 launch.",
    icon: "/logos/java.svg",
    aspect: 1,
    gitLink: "https://github.com/openjdk/jdk",
  },
  {
    name: "Jenkins",
    industry: "CI/CD platform",
    founded: 2011,
    funFact:
      "Jenkins began life as Hudson, but was renamed after a 2011 trademark dispute with Oracle, with the community picking a new name via an open vote.",
    icon: "/logos/jenkins.svg",
    aspect: 1,
    gitLink: "https://github.com/jenkinsci/jenkins",
  },
  {
    name: "jQuery",
    industry: "JavaScript library",
    founded: 2006,
    funFact: "John Resig introduced jQuery at BarCamp NYC in January 2006 under the tagline 'write less, do more'.",
    icon: "/logos/jquery.svg",
    aspect: 1,
    gitLink: "https://github.com/jquery/jquery",
  },
  {
    name: "JSON",
    industry: "Data interchange format",
    founded: 2001,
    funFact:
      "JSON was specified by Douglas Crockford, who extracted the format from a subset of JavaScript's own object-literal syntax rather than inventing something new.",
    icon: "/logos/json.svg",
    aspect: 1,
    gitLink: "https://github.com/douglascrockford/JSON-js",
  },
  {
    name: "JUnit",
    industry: "Testing framework",
    founded: 1997,
    funFact:
      "Kent Beck and Erich Gamma wrote the first version of JUnit together during a plane flight, using the trip specifically to pair-program the framework.",
    icon: "/logos/junit.svg",
    aspect: 1,
    gitLink: "https://github.com/junit-team/junit5",
  },
  {
    name: "JWT",
    industry: "Authentication standard",
    founded: 2015,
    funFact:
      "JWT was standardized as RFC 7519, and its compact form is just three base64url-encoded segments (header, payload, and signature) joined by dots.",
    icon: "/logos/jwt.svg",
    aspect: 0.996,
    gitLink: "https://github.com/jwt",
  },
  {
    name: "Keycloak",
    industry: "Identity and access management",
    founded: 2014,
    funFact:
      "Keycloak, built at Red Hat, later became the upstream project for Red Hat's own SSO product, which was fully rebranded as Red Hat build of Keycloak in 2023.",
    icon: "/logos/keycloak.svg",
    aspect: 1.113,
    gitLink: "https://github.com/keycloak/keycloak",
  },
  {
    name: "Lodash",
    industry: "Utility library",
    founded: 2012,
    funFact:
      "Lodash began as a fork of Underscore.js created by John-David Dalton to fix performance and consistency issues, and it eventually became more widely used than the library it forked from.",
    icon: "/logos/lodash.svg",
    aspect: 1,
    gitLink: "https://github.com/lodash/lodash",
  },
  {
    name: "Markdown",
    industry: "Markup language",
    founded: 2004,
    funFact:
      "Markdown was created in 2004 by John Gruber with help from Aaron Swartz, who had already built a similar plain-text markup language called atx and helped shape features like the '#' heading syntax.",
    icon: "/logos/markdown.svg",
    aspect: 1.62,
    gitLink: "https://github.com/mundimark/markdown.pl",
  },
  {
    name: "MDX",
    industry: "Markdown/JSX format",
    founded: 2018,
    funFact:
      "MDX lets developers write JSX directly inside Markdown documents, and it grew out of work at ZEIT (now Vercel) to make documentation sites more interactive.",
    icon: "/logos/mdx.svg",
    aspect: 2.415,
    gitLink: "https://github.com/mdx-js/mdx",
  },
  {
    name: "MongoDB",
    industry: "NoSQL database",
    founded: 2009,
    funFact:
      "MongoDB stores data as flexible, JSON-like BSON documents instead of rows and tables, and was originally built as part of a planned platform-as-a-service by 10gen before the database itself became the main product.",
    icon: "/logos/mongodb.svg",
    aspect: 1,
    gitLink: "https://github.com/mongodb/mongo",
  },
  {
    name: "Neo4j",
    industry: "Graph database",
    founded: 2007,
    funFact:
      "Neo4j's founders first sketched the idea for a graph database on the back of a napkin during a flight in 2000, but didn't found the company behind it until 2007.",
    icon: "/logos/neo4j.svg",
    aspect: 1,
    gitLink: "https://github.com/neo4j/neo4j",
  },
  {
    name: "NgRx",
    industry: "State management library",
    founded: 2016,
    funFact:
      "NgRx started as a small experiment by Rob Wormald, Mike Ryan, and Brandon Roberts to bring Redux-style state management to Angular during the Angular 2 rewrite.",
    icon: "/logos/ngrx.svg",
    aspect: 1,
    gitLink: "https://github.com/ngrx/platform",
  },
  {
    name: "Node.js",
    industry: "JavaScript runtime",
    founded: 2009,
    funFact:
      "Node.js was created by Ryan Dahl, who was frustrated that most web servers of the time couldn't handle many simultaneous connections efficiently, and built it on Chrome's V8 engine to fix that.",
    icon: "/logos/nodejs.svg",
    aspect: 1,
    gitLink: "https://github.com/nodejs/node",
  },
  {
    name: "Open Source Initiative",
    industry: "Nonprofit standards organization",
    founded: 1998,
    funFact:
      "The Open Source Initiative was founded in February 1998 by Bruce Perens and Eric S. Raymond, inspired by Netscape's decision to release the source code of its Communicator browser.",
    icon: "/logos/opensource.svg",
    aspect: 1.032,
    gitLink: "https://github.com/opensourceorg",
  },
  {
    name: "PixiJS",
    industry: "2D rendering engine",
    founded: 2013,
    funFact:
      "PixiJS was created by Mat Groves and the Goodboy Digital team in 2013 with a focus on making fast, GPU-accelerated 2D rendering accessible in the browser.",
    icon: "/logos/pixijs.svg",
    aspect: 1,
    gitLink: "https://github.com/pixijs/pixijs",
  },
  {
    name: "pnpm",
    industry: "Package manager",
    founded: 2017,
    funFact:
      "pnpm saves disk space by storing every package version once in a global content-addressable store and hard-linking it into projects, instead of duplicating files in every node_modules folder.",
    icon: "/logos/pnpm.svg",
    aspect: 1,
    gitLink: "https://github.com/pnpm/pnpm",
  },
  {
    name: "PrimeNG",
    industry: "UI component library",
    founded: 2016,
    funFact:
      "PrimeNG is built by PrimeTek, the same team behind the long-running PrimeFaces and PrimeVue UI libraries for other frameworks, and was rewritten for the Angular 2+ era.",
    icon: "/logos/primeng.svg",
    aspect: 1,
    gitLink: "https://github.com/primefaces/primeng",
  },
  {
    name: "Prometheus",
    industry: "Monitoring system",
    founded: 2012,
    funFact:
      "Prometheus was built at SoundCloud in 2012, drawing heavy inspiration from Google's internal monitoring tool Borgmon, and is named after the Greek Titan who gave fire to humanity.",
    icon: "/logos/prometheus.svg",
    aspect: 1,
    gitLink: "https://github.com/prometheus/prometheus",
  },
  {
    name: "Pug",
    industry: "Templating engine",
    founded: 2010,
    funFact:
      "Pug was originally called Jade, but the project had to rename itself in 2016 after discovering 'Jade' was already a registered trademark.",
    icon: "/logos/pug.svg",
    aspect: 1,
    gitLink: "https://github.com/pugjs/pug",
  },
  {
    name: "Pulumi",
    industry: "Infrastructure as code",
    founded: 2017,
    funFact:
      "Pulumi was founded by Joe Duffy, who previously led Microsoft's Midori research OS project, so developers could write cloud infrastructure in general-purpose languages instead of a DSL like Terraform's HCL.",
    icon: "/logos/pulumi.svg",
    aspect: 1,
    gitLink: "https://github.com/pulumi/pulumi",
  },
  {
    name: "Quarkus",
    industry: "Java framework",
    founded: 2019,
    funFact:
      "Quarkus brands itself 'Supersonic Subatomic Java' and was built by Red Hat specifically to shrink Java's startup time and memory footprint for containers and serverless.",
    icon: "/logos/quarkus.svg",
    aspect: 1,
    gitLink: "https://github.com/quarkusio/quarkus",
  },
  {
    name: "RSS",
    industry: "Web syndication format",
    founded: 1999,
    funFact:
      "After Netscape's original 1999 RSS format was abandoned, Dave Winer's UserLand and an independent RSS-DEV working group each revived it separately, producing the rival 2.0 and 1.0 branches still in use today.",
    icon: "/logos/rss.svg",
    aspect: 1,
    gitLink: "https://github.com/w3c/feedvalidator",
  },
  {
    name: "Ruby on Rails",
    industry: "Ruby web framework",
    founded: 2004,
    funFact:
      "Rails was extracted by David Heinemeier Hansson from the codebase of Basecamp, the project-management tool he was building at the agency then called 37signals.",
    icon: "/logos/rails.svg",
    aspect: 1,
    gitLink: "https://github.com/rails/rails",
  },
  {
    name: "Rust",
    industry: "Programming language",
    founded: 2010,
    funFact:
      "Rust began as Graydon Hoare's personal side project in 2006 before Mozilla sponsored it, and he first publicly unveiled it at Mozilla's 2010 Annual Summit.",
    icon: "/logos/rust.svg",
    aspect: 1,
    gitLink: "https://github.com/rust-lang/rust",
  },
  {
    name: "Selenium",
    industry: "Browser automation framework",
    founded: 2004,
    funFact:
      "Selenium got its name as a joking jab at a rival commercial testing tool called Mercury: selenium is a chemical antidote to mercury poisoning.",
    icon: "/logos/selenium.svg",
    aspect: 1,
    gitLink: "https://github.com/SeleniumHQ/selenium",
  },
  {
    name: "Solidity",
    industry: "Smart contract language",
    founded: 2014,
    funFact:
      "Solidity was designed for the Ethereum Virtual Machine by Gavin Wood, Christian Reitwiessner, and others, with syntax deliberately modeled on JavaScript and C++ to feel familiar to existing developers.",
    icon: "/logos/solidity.svg",
    aspect: 1,
    gitLink: "https://github.com/ethereum/solidity",
  },
  {
    name: "SolidJS",
    industry: "JavaScript framework",
    founded: 2018,
    funFact:
      "SolidJS was created by Ryan Carniato and compiles JSX directly into real DOM updates using fine-grained reactivity, skipping the virtual DOM that frameworks like React rely on.",
    icon: "/logos/solidjs.svg",
    aspect: 1,
    gitLink: "https://github.com/solidjs/solid",
  },
  {
    name: "SonarQube",
    industry: "Code quality platform",
    founded: 2007,
    funFact:
      "SonarQube was started by Simon Brandhof in 2007 to unify a handful of fragmented open-source Java code-quality tools into a single platform, before expanding to cover 30+ languages.",
    icon: "/logos/sonarqube.svg",
    aspect: 1,
    gitLink: "https://github.com/SonarSource/sonarqube",
  },
  {
    name: "SQLite",
    industry: "Relational database",
    founded: 2000,
    funFact:
      "SQLite's creator D. Richard Hipp also built Fossil, a distributed version control system, specifically to manage SQLite's own source code and development history.",
    icon: "/logos/sqlite.svg",
    aspect: 1,
    gitLink: "https://github.com/sqlite/sqlite",
  },
  {
    name: "styled-components",
    industry: "CSS-in-JS library",
    founded: 2016,
    funFact:
      "styled-components was first announced on stage at ParisReact in 2016 by creators Max Stoiber and Glen Maddern as a way to write real CSS scoped to a component without class-name collisions.",
    icon: "/logos/styledcomponents.svg",
    aspect: 1,
    gitLink: "https://github.com/styled-components/styled-components",
  },
  {
    name: "SVG",
    industry: "Vector graphics format",
    founded: 2001,
    funFact:
      "SVG's XML-based design meant that, unlike earlier binary vector formats, an image could be opened as plain text and styled directly with CSS.",
    icon: "/logos/svg.svg",
    aspect: 1,
    gitLink: "https://github.com/w3c/svgwg",
  },
  {
    name: "Swagger",
    industry: "API development tooling",
    founded: 2011,
    funFact:
      "Swagger UI turns an OpenAPI definition into interactive, try-it-yourself API documentation rendered directly in the browser, without anyone having to hand-write docs.",
    icon: "/logos/swagger.svg",
    aspect: 1,
    gitLink: "https://github.com/swagger-api/swagger-ui",
  },
  {
    name: "tRPC",
    industry: "TypeScript API library",
    founded: 2020,
    funFact:
      "tRPC began as a proof-of-concept called ZodRPC, built by Zod creator Colin McDonnell and then abandoned, until Alex 'KATT' Johansson found the repo and grew it into tRPC.",
    icon: "/logos/trpc.svg",
    aspect: 1,
    gitLink: "https://github.com/trpc/trpc",
  },
  {
    name: "TypeScript",
    industry: "Typed superset of JavaScript",
    founded: 2012,
    funFact:
      "TypeScript was designed by Anders Hejlsberg, who also created C# and Turbo Pascal, to add optional static typing to JavaScript for Microsoft's own large codebases.",
    icon: "/logos/typescript.svg",
    aspect: 1,
    gitLink: "https://github.com/microsoft/TypeScript",
  },
  {
    name: "Waku",
    industry: "React framework",
    founded: 2023,
    funFact:
      "Waku was created by Daishi Kato, the same developer behind the state-management libraries Zustand and Jotai, as a minimal framework built around React Server Components.",
    icon: "/logos/waku.svg",
    aspect: 1,
    gitLink: "https://github.com/wakujs/waku",
  },
  {
    name: "Web Components",
    industry: "Web platform standard",
    founded: 2011,
    funFact:
      "Web Components was first proposed by Google's Alex Russell at the Fronteers Conference in 2011, bundling several separate specs, including Custom Elements, Shadow DOM, and HTML Templates, into one component model.",
    icon: "/logos/webcomponents.svg",
    aspect: 1.225,
    gitLink: "https://github.com/WICG/webcomponents",
  },
  {
    name: "WebGPU",
    industry: "Browser graphics API",
    founded: 2017,
    funFact:
      "WebGPU was designed as a modern successor to WebGL, giving web pages low-level GPU access, including compute shaders, that mirrors native APIs like Vulkan, Metal, and Direct3D 12.",
    icon: "/logos/webgpu.svg",
    aspect: 1.225,
    gitLink: "https://github.com/gpuweb/gpuweb",
  },
  {
    name: "Webhooks",
    industry: "HTTP callback pattern",
    founded: 2007,
    funFact:
      "The term 'webhook' was coined in 2007 by Jeff Lindsay, a hackathon-era portmanteau of 'web' and the programming concept of a callback 'hook'.",
    icon: "/logos/webhooks.svg",
    aspect: 1.071,
    gitLink: "https://github.com/standard-webhooks/standard-webhooks",
  },
  {
    name: "webpack",
    industry: "JavaScript bundler",
    founded: 2012,
    funFact:
      "webpack popularized treating every asset, including CSS, images, and fonts, as a module that JavaScript could require() directly, code-splitting them on demand.",
    icon: "/logos/webpack.svg",
    aspect: 1,
    gitLink: "https://github.com/webpack/webpack",
  },
  {
    name: "WebRTC",
    industry: "Real-time communication API",
    founded: 2011,
    funFact:
      "WebRTC was open-sourced by Google in 2011 after its acquisition of Global IP Solutions, and it's the technology underneath most in-browser video calling, including Google Meet and Discord's web client.",
    icon: "/logos/webrtc.svg",
    aspect: 1.028,
    gitLink: "https://github.com/w3c/webrtc-pc",
  },
  {
    name: "WebSocket",
    industry: "Real-time communication protocol",
    founded: 2011,
    funFact:
      "WebSocket was standardized as RFC 6455 in 2011, giving browsers full-duplex, persistent connections instead of the endless HTTP polling hacks developers used before it.",
    icon: "/logos/websocket.svg",
    aspect: 1.326,
    gitLink: "https://github.com/whatwg/websockets",
  },
  {
    name: "WordPress",
    industry: "Content management system",
    founded: 2003,
    funFact:
      "WordPress began in 2003 as a fork of an abandoned blogging tool called b2/cafelog, started by Matt Mullenweg and Mike Little.",
    icon: "/logos/wordpress.svg",
    aspect: 1,
    gitLink: "https://github.com/WordPress/WordPress",
  },
  {
    name: "Zend Framework",
    industry: "PHP framework",
    founded: 2006,
    funFact:
      "Zend is a portmanteau of founders Zeev Suraski and Andi Gutmans' first names, the same two engineers who had already built the Zend Engine that powers PHP itself.",
    icon: "/logos/zend.svg",
    aspect: 1,
    gitLink: "https://github.com/zendframework/zendframework",
  },
  {
    name: "Zustand",
    industry: "State management library",
    founded: 2019,
    funFact:
      "Zustand, German for 'state', was built by the pmndrs collective, the same group behind react-spring, and needs no context provider wrapping the app.",
    icon: "/logos/zustand.svg",
    aspect: 1,
    gitLink: "https://github.com/pmndrs/zustand",
  },
  {
    name: "Alpine.js",
    industry: "JavaScript framework",
    founded: 2019,
    funFact:
      "Alpine.js was created by Caleb Porzio as a lightweight way to add Vue-like reactivity straight in HTML, and its README once described it as 'Tailwind for JavaScript'.",
    icon: "/logos/alpinejs.svg",
    aspect: 2.169,
    gitLink: "https://github.com/alpinejs/alpine",
  },
  {
    name: "CakePHP",
    industry: "PHP framework",
    founded: 2005,
    funFact:
      "CakePHP began as a minimal framework called 'Cake', written by Polish developer Michal Tatarynowicz and explicitly modeled after Ruby on Rails.",
    icon: "/logos/cakephp.svg",
    aspect: 1.28,
    gitLink: "https://github.com/cakephp/cakephp",
  },
]
